;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-forward-char
        evil-mouse-drag-region
        evil-normal-state
        evil-previous-line
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-delete-backward-char-and-join
        evil-next-line
        ))
